### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by unclepis** [aotianwinter/my-auto-deploy#2]
# 问题
配置了一下服务器的host，port，username和password，在ssh登录的时候提示连接失败 Error: All configured authentication methods failed，请问有解决方案么？搜了一下没有找到怎么解决...

# 错误信息
正在检查全局配置信息...
? Which project do you want to deploy? client57
您选择了部署 client57
1-正在压缩文件...
2-压缩完成！共计 0.000MB
3-168.23.122.57 连接失败 Error: All configured authentication methods failed
    at doNextAuth (D:\client-app\autoDeploy\node_modules\ssh2\lib\client.js:413:17)
    at tryNextAuth (D:\client-app\autoDeploy\node_modules\ssh2\lib\client.js:484:5)
    at SSH2Stream.onUSERAUTH_FAILURE (D:\client-app\autoDeploy\node_modules\ssh2\lib\client.js:597:5)
    at SSH2Stream.emit (events.js:223:5)
    at parsePacket (D:\client-app\autoDeploy\node_modules\ssh2-streams\lib\ssh.js:3779:10)
    at SSH2Stream._transform (D:\client-app\autoDeploy\node_modules\ssh2-streams\lib\ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (D:\client-app\autoDeploy\node_modules\ssh2-streams\lib\ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:435:12) {
  level: 'client-authentication'
}

**Comment by aotianwinter** [comment]
请确保登录服务器的用户名、密码正确，当用户名、密码不正确时，会出现该提示。

**Comment by unclepis** [comment]
> 请确保登录服务器的用户名、密码正确，当用户名、密码不正确时，会出现该提示。

查了node-ssh的配置，增加了一个port端口，我用finalshell这种远程工具通过账号密码登录是可以登录的，也就是说用户名密码应该没有错。。

**Comment by aotianwinter** [comment]
配置文件中默认使用22端口登录，无需填写，端口配置稍后更新。

**Comment by unclepis** [comment]
> 配置文件中默认使用22端口登录，无需填写，端口配置稍后更新。

嗯，我们部署的服务器对ssh链接暴漏的是别的端口，所以我增加了配置port，我看了一下node-ssh的issue，感觉好像是服务器不支持通过这种方式ssh接入。

**Comment by aotianwinter** [comment]
你好，本地测试发现，修改端口可以正常连接和上传文件（服务器防火墙已加入白名单）。
更新已支持修改连接端口，ssh私钥连接，可以尝试是否正常连接服务器。

**Comment by unclepis** [comment]
> 你好，本地测试发现，修改端口可以正常连接和上传文件（服务器防火墙已加入白名单）。
> 更新已支持修改连接端口，ssh私钥连接，可以尝试是否正常连接服务器。

大佬，方便加个微信咨询几个小问题么？我添加了你微信请通过一下
