### ISSUE TITLE
你好，我本地部署时报错了，不知道什么原因

### ISSUE THREAD

**Issue by Somi1** [aotianwinter/my-auto-deploy#4]
![image](https://user-images.githubusercontent.com/22066494/82164690-656f9b80-98e4-11ea-9acf-c5b42afd6f83.png)

**Comment by Somi1** [comment]
部署过程出现错误！ TypeError: sshServer.connectServe is not a function
    at main (D:\2.0\04-WEB\rz_operation\app.js:26:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by aotianwinter** [comment]
尝试重新拉取下代码，我这里查看了ssh.js的代码，connectServe可作为函数调用，若还是不行可添加我的微信沟通解决。
微信号：aotianwinter
